---
title: "project"
output: html_document
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
```

```{r}
library("dplyr")
library(datasets)
```

```{r}
use_r("umapgp")
```
```{r}
use_package("datasets")
```
```{r}
use_package("ggplot2")
```
```{r}
use_testthat()
```

```{r}
use_package("dplyr1")
```

```{r}
install.packages("ggplot2")
```
```{r}
data("iris")
```

```{r}
library(ggplot2)
```

```{r}
use_package("devtools")
```

```{r}
data("iris")
iris
```

# Visualizing the dataset
```{r}
ggplot(data = iris, aes(x = Petal.Length, y = Petal.Width))+
  xlab("Petal Length")+
  ylab("Petal Width") +
  geom_point(aes(color = Species,shape=Species))+
  geom_smooth(method='lm')+
  ggtitle("Iris Petal Length vs Width")
```

# Perprocessing the data for umap
```{r}
# Adding a unique row ID
iris <- iris %>%
  mutate(ID=row_number())

# Creating a dataframe with all categorical variables with the unique row ID

iris_meta <- iris %>%
  select(ID, Species)

```

# Performing UMAP
```{r}
set.seed(142)
umap_fit <- iris %>%
  select(where(is.numeric)) %>%
  column_to_rownames("ID") %>%
  scale() %>%
  umap()
umap_df <- umap_fit$layout %>%
  as.data.frame()%>%
  rename(UMAP1="V1",
         UMAP2="V2") %>%
  mutate(ID=row_number())%>%
  inner_join(iris_meta, by="ID")
```

# UMAP Plot
```{r}
umap_df %>%
  ggplot(aes(x = UMAP1,
             y = UMAP2,
             color = Species))+
  geom_point()+
  labs(x = "UMAP1",
       y = "UMAP2",
      subtitle = "UMAP plot")
```

```{r}
use_package("magrittr")
```

```{r}
a<-force(morley)
a



```
```{r}
library(datasets::)
```

```{r}
library(utils)
```

```{r}
force(data("mtcars"))
```

```{r}
use_package("umap")
```


```{r}
use_test("UMAP")
```







